SELECT *
WHERE {
  {
    {
      ?item <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q486972>.
    }
    UNION
    {
      ?item <http://www.wikidata.org/prop/direct/P31> ?instanceOf.
      ?instanceOf (<http://www.wikidata.org/prop/direct/P279>+) <http://www.wikidata.org/entity/Q486972>.
    }
  }
}
