PREFIX : <http://x>

SELECT * WHERE {
    {
        { ?s :labelA ?pLabel }
        {{ ?s :labelC ?Label }
        UNION
        { ?s :labelD ?label }}
    }
    UNION
    {
        { ?s :labelB ?pLabel }
        {{ ?s :labelC ?Label }
        UNION
        { ?s :labelD ?label }}
    }
}
