"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// TODO: add aggregates?
// TODO: can't find a way to use these values as string types in the interfaces
exports.Algebra = Object.freeze({
    AGGREGATE: 'aggregate',
    ALT: 'alt',
    BGP: 'bgp',
    DESC: 'desc',
    DISTINCT: 'distinct',
    EXISTS: 'exists',
    EXTEND: 'extend',
    FILTER: 'filter',
    FN_NOT: 'fn:not',
    GRAPH: 'graph',
    GROUP: 'group',
    INV: 'inv',
    JOIN: 'join',
    LEFT_JOIN: 'leftjoin',
    LINK: 'link',
    MINUS: 'minus',
    NOT_EXISTS: 'notexists',
    NPS: 'nps',
    ONE_OR_MORE_PATH: 'OneOrMorePath',
    ORDER_BY: 'orderby',
    PATH: 'path',
    PROJECT: 'project',
    REDUCED: 'reduced',
    ROW: 'row',
    SEQ: 'seq',
    SEQUENCE: 'sequence',
    SLICE: 'slice',
    TABLE: 'table',
    TRIPLE: 'triple',
    TO_MULTISET: 'tomultiset',
    UNION: 'union',
    UNIT: 'unit',
    VARS: 'vars',
    VALUES: 'values',
    ZERO_OR_MORE_PATH: 'ZeroOrMorePath',
    ZERO_OR_ONE_PATH: 'ZeroOrOnePath',
});
//# sourceMappingURL=algebra.js.map